"use client";

import { use, useEffect, useState } from "react";
import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { StatusBadge } from "@/components/compliance/status-badge";
import { Separator } from "@/components/ui/separator";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import {
  Download, Printer, Loader2, AlertCircle,
} from "lucide-react";
import { PreviousButton } from "@/components/shared/previous-button";
import {
  fetchBackendTenderById,
  fetchTenderRequirements,
  fetchGroundTruthBenchmarks,
  fetchGroundTruthBidders,
  BackendTender,
  StructuredRequirement,
  GroundTruthBenchmark,
} from "@/lib/api-client";

export default function EvaluationReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const decodedId = decodeURIComponent(id);

  const [tender, setTender] = useState<BackendTender | null>(null);
  const [requirements, setRequirements] = useState<StructuredRequirement[]>([]);
  const [benchmarks, setBenchmarks] = useState<GroundTruthBenchmark[]>([]);
  const [bidders, setBidders] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadData() {
      setLoading(true);
      setError(null);
      try {
        const [tenderData, reqData, benchData, bidderData] = await Promise.all([
          fetchBackendTenderById(decodedId),
          fetchTenderRequirements(decodedId).catch(() => ({ items: [], total: 0 })),
          fetchGroundTruthBenchmarks().catch(() => ({ items: [], total: 0 })),
          fetchGroundTruthBidders().catch(() => ({ items: [], total: 0 })),
        ]);
        setTender(tenderData);
        setRequirements(reqData.items || []);
        setBenchmarks(benchData.items || []);
        setBidders(bidderData.items || []);
      } catch (err: any) {
        console.error("Failed to load evaluation report data:", err);
        setError(err.message || "Failed to load evaluation report.");
      } finally {
        setLoading(false);
      }
    }
    loadData();
  }, [decodedId]);

  if (loading) {
    return (
      <div className="p-12 text-center flex flex-col items-center justify-center gap-3">
        <Loader2 className="h-6 w-6 animate-spin text-[#1e3a5f]" />
        <p className="text-sm text-muted-foreground">Generating evaluation report from backend...</p>
      </div>
    );
  }

  if (error || !tender) {
    return (
      <div className="p-6 max-w-4xl mx-auto space-y-4">
        <PreviousButton fallbackHref="/officer/reports" />
        <div className="bg-rose-50 border border-rose-200 text-rose-800 text-sm p-4 rounded-lg flex items-center gap-2">
          <AlertCircle className="w-5 h-5 text-rose-600 shrink-0" />
          <span>{error || "Tender not found in database."}</span>
        </div>
      </div>
    );
  }

  // Filter bidders for this tender
  const tenderBidders = bidders.filter(
    (b) =>
      b.tenderId === tender.id ||
      b.tenderId === tender.tender_number ||
      (tender.tender_number === "GEM/2026/B/7261466" && b.tenderId === "tender-t1") ||
      (tender.tender_number === "GEM/2026/B/7364888" && b.tenderId === "tender-t2") ||
      (tender.tender_number === "GEM/2026/B/7676747" && b.tenderId === "tender-t3")
  );

  return (
    <div className="p-4 sm:p-6 space-y-4 sm:space-y-6 max-w-4xl mx-auto">
      {/* Breadcrumb & Navigation */}
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div className="flex flex-wrap items-center gap-2 text-xs sm:text-sm">
          <Link href="/officer" className="text-muted-foreground hover:text-foreground">Dashboard</Link>
          <span className="text-muted-foreground">/</span>
          <Link href={`/officer/tenders/${encodeURIComponent(tender.tender_number || tender.id)}`} className="text-muted-foreground hover:text-foreground">
            Evaluation
          </Link>
          <span className="text-muted-foreground">/</span>
          <span className="font-medium text-foreground">Report</span>
        </div>
        <PreviousButton fallbackHref={`/officer/tenders/${encodeURIComponent(tender.tender_number || tender.id)}`} />
      </div>

      {/* Report Header */}
      <Card>
        <CardContent className="p-4 sm:p-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4">
            <div>
              <h1 className="text-lg sm:text-xl font-bold text-[#1e3a5f]">Bid Evaluation &amp; Compliance Report</h1>
              <p className="text-xs sm:text-sm text-muted-foreground">Generated by SatyaSetu · GeM Public Procurement Engine</p>
            </div>
            <div className="flex items-center gap-2 self-start sm:self-auto">
              <Button variant="outline" size="sm" className="gap-1 text-xs" onClick={() => window.print()}>
                <Printer className="h-3.5 w-3.5" /> Print
              </Button>
              <Button size="sm" className="bg-[#1e3a5f] hover:bg-[#152a45] gap-1 text-xs" onClick={() => window.print()}>
                <Download className="h-3.5 w-3.5" /> Export PDF
              </Button>
            </div>
          </div>

          <Separator className="my-4" />

          {/* Tender Metadata */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4 text-xs sm:text-sm">
            <div>
              <p className="text-xs text-muted-foreground">Tender Number</p>
              <p className="font-mono font-bold text-slate-800 mt-0.5">{tender.tender_number}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Estimated Value</p>
              <p className="font-bold text-slate-900 mt-0.5">₹{(tender.estimated_value / 100000).toFixed(2)} Lakh</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Tender Status</p>
              <Badge variant="outline" className="mt-0.5 text-xs bg-emerald-50 text-emerald-700 border-emerald-200">
                {tender.status}
              </Badge>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Requirements Count</p>
              <p className="font-bold text-slate-900 mt-0.5">{requirements.length} Clauses</p>
            </div>
          </div>

          <div className="mt-3 pt-3 border-t text-xs">
            <span className="text-muted-foreground">Title: </span>
            <span className="font-medium text-slate-900">{tender.title}</span>
            <span className="text-muted-foreground"> · Buyer: </span>
            <span className="font-medium text-slate-900">{tender.organization}</span>
          </div>
        </CardContent>
      </Card>

      {/* Bidder Evaluation Summary */}
      <Card>
        <CardContent className="p-4 sm:p-6 space-y-3">
          <h2 className="font-semibold text-sm sm:text-base text-slate-900">Bidder Compliance &amp; Benchmark Summary</h2>
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="min-w-[160px]">Bidder Entity</TableHead>
                  <TableHead className="w-[100px]">Code</TableHead>
                  <TableHead className="w-[140px]">Overall Status</TableHead>
                  <TableHead className="w-[110px]">Score</TableHead>
                  <TableHead className="w-[110px]">Risk Level</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {tenderBidders.map((bidder) => {
                  const bench = benchmarks.find((b) => b.bidderId === bidder.id || b.bidderCode === bidder.bidderCode);

                  return (
                    <TableRow key={bidder.id}>
                      <TableCell className="font-semibold text-xs text-slate-900">
                        {bidder.legalName}
                      </TableCell>
                      <TableCell className="font-mono text-xs text-slate-700">
                        {bidder.bidderCode}
                      </TableCell>
                      <TableCell>
                        <StatusBadge status={bench?.expectedOverallStatus || "REVIEW"} size="sm" />
                      </TableCell>
                      <TableCell className="font-bold text-xs">
                        {bench ? `${bench.expectedComplianceScore}%` : "—"}
                      </TableCell>
                      <TableCell>
                        <Badge
                          variant="outline"
                          className={`text-[10px] ${
                            bench?.expectedRiskLevel === "LOW"
                              ? "bg-emerald-50 text-emerald-700 border-emerald-200"
                              : bench?.expectedRiskLevel === "HIGH" || bench?.expectedRiskLevel === "CRITICAL"
                              ? "bg-rose-50 text-rose-700 border-rose-200"
                              : "bg-amber-50 text-amber-700 border-amber-200"
                          }`}
                        >
                          {bench?.expectedRiskLevel || "MEDIUM"}
                        </Badge>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
