"use client";

import { use } from "react";
import Link from "next/link";
import { getTenderById } from "@/data/tenders";
import { getBidsByTender } from "@/data/bids";
import { getComplianceByTender } from "@/data/compliance";
import { riskAssessments, aiRecommendations } from "@/data/risk-and-recommendations";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/compliance/status-badge";
import { Separator } from "@/components/ui/separator";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import {
  Download, Printer,
} from "lucide-react";

export default function EvaluationReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const tender = getTenderById(id);
  const bids = getBidsByTender(id);
  const compliance = getComplianceByTender(id);

  if (!tender) return <div className="p-6">Tender not found.</div>;

  return (
    <div className="p-4 sm:p-6 space-y-4 sm:space-y-6 max-w-4xl mx-auto">
      {/* Breadcrumb */}
      <div className="flex flex-wrap items-center gap-2 text-xs sm:text-sm">
        <Link href="/officer" className="text-muted-foreground hover:text-foreground">Dashboard</Link>
        <span className="text-muted-foreground">/</span>
        <Link href={`/officer/tenders/${id}`} className="text-muted-foreground hover:text-foreground">Evaluation</Link>
        <span className="text-muted-foreground">/</span>
        <span className="font-medium text-foreground">Report</span>
      </div>

      {/* Report Header */}
      <Card>
        <CardContent className="p-4 sm:p-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4">
            <div>
              <h1 className="text-lg sm:text-xl font-bold text-[#1e3a5f]">Bid Evaluation Report</h1>
              <p className="text-xs sm:text-sm text-muted-foreground">Generated by SatyaSetu · Prototype Report</p>
            </div>
            <div className="flex items-center gap-2 self-start sm:self-auto">
              <Button variant="outline" size="sm" className="gap-1 text-xs" onClick={() => window.print()}>
                <Printer className="h-3.5 w-3.5" /> Print
              </Button>
              <Button size="sm" className="bg-[#1e3a5f] hover:bg-[#152a45] gap-1 text-xs">
                <Download className="h-3.5 w-3.5" /> Export PDF
              </Button>
            </div>
          </div>

          {/* Tender Details */}
          <div className="rounded-md border p-3.5 sm:p-4 space-y-2 mb-4 bg-card">
            <h2 className="text-xs sm:text-sm font-semibold">1. Tender Details</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs sm:text-sm">
              <div className="flex justify-between items-start gap-2"><span className="text-muted-foreground shrink-0">Tender ID</span><span className="font-mono">{tender.id}</span></div>
              <div className="flex justify-between items-start gap-2"><span className="text-muted-foreground shrink-0">Organization</span><span className="text-right">{tender.organization}</span></div>
              <div className="flex justify-between items-start gap-2 sm:col-span-2"><span className="text-muted-foreground shrink-0">Title</span><span className="text-right">{tender.title}</span></div>
              <div className="flex justify-between items-start gap-2"><span className="text-muted-foreground shrink-0">Value</span><span className="font-semibold">{tender.estimatedValueFormatted}</span></div>
            </div>
          </div>

          {/* Bidder Summary */}
          <div className="rounded-md border p-3.5 sm:p-4 mb-4 bg-card">
            <h2 className="text-xs sm:text-sm font-semibold mb-3">2. Bidder Evaluation Summary</h2>
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="min-w-[140px]">Bidder</TableHead>
                    <TableHead>Compliance</TableHead>
                    <TableHead>Risk</TableHead>
                    <TableHead className="min-w-[100px]">Commercial</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead className="min-w-[130px]">Recommendation</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {bids.map((bid) => {
                    const comp = compliance.find(c => c.bidderId === bid.bidderId);
                    const risk = riskAssessments.find(r => r.bidderId === bid.bidderId);
                    const rec = aiRecommendations.find(r => r.bidderId === bid.bidderId);
                    return (
                      <TableRow key={bid.id}>
                        <TableCell className="font-medium text-xs sm:text-sm">{bid.bidder.shortName}</TableCell>
                        <TableCell className="font-bold text-xs sm:text-sm">{comp?.complianceScore}%</TableCell>
                        <TableCell><StatusBadge status={risk?.riskLevel ?? "LOW"} size="sm" showIcon={false} /></TableCell>
                        <TableCell className="text-xs sm:text-sm whitespace-nowrap">{bid.commercial.totalAmountFormatted}</TableCell>
                        <TableCell><StatusBadge status={comp?.overallStatus ?? "PASS"} size="sm" /></TableCell>
                        <TableCell><StatusBadge status={rec?.recommendation ?? "QUALIFY"} size="sm" /></TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>
          </div>

          {/* Sections */}
          {["3. Requirement Compliance Details", "4. Document Verification Summary", "5. Government Verification Status", "6. Risk Assessment", "7. AI Recommendations"].map((section) => (
            <div key={section} className="rounded-md border p-3.5 sm:p-4 mb-4 bg-card">
              <h2 className="text-xs sm:text-sm font-semibold">{section}</h2>
              <p className="text-xs text-muted-foreground mt-1">
                Detailed {section.toLowerCase().split(". ")[1]} information available in full report export.
              </p>
            </div>
          ))}

          {/* Officer Decision */}
          <div className="rounded-md border p-3.5 sm:p-4 mb-4 bg-card">
            <h2 className="text-xs sm:text-sm font-semibold">8. Officer Decision</h2>
            <p className="text-xs text-muted-foreground mt-1 leading-relaxed">
              Final procurement decisions are recorded by the authorized Procurement Officer
              and are binding as per applicable government procurement rules.
            </p>
          </div>

          {/* Audit Trail */}
          <div className="rounded-md border p-3.5 sm:p-4 bg-card">
            <h2 className="text-xs sm:text-sm font-semibold">9. Audit Trail</h2>
            <p className="text-xs text-muted-foreground mt-1 leading-relaxed">
              Complete audit trail with timestamps, actors, and actions is maintained for
              every bid evaluation. This ensures full traceability and accountability.
            </p>
          </div>

          <Separator className="my-4" />

          <div className="text-center px-2">
            <p className="text-[10px] sm:text-[11px] text-muted-foreground leading-relaxed">
              This report was generated by SatyaSetu — Prototype for Smart India Hackathon 2026.
              <br />
              All verification sources are mock/prototype implementations. AI recommendations are advisory only.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
