"use client";

import { use } from "react";
import Link from "next/link";
import { getTenderById } from "@/data/tenders";
import { getBidsByTender } from "@/data/bids";
import { getComplianceByTender } from "@/data/compliance";
import { riskAssessments, aiRecommendations } from "@/data/risk-and-recommendations";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { StatusBadge } from "@/components/compliance/status-badge";
import { Separator } from "@/components/ui/separator";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import {
  FileText, Download, Printer, Calendar, Building2, IndianRupee,
} from "lucide-react";

export default function EvaluationReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const tender = getTenderById(id);
  const bids = getBidsByTender(id);
  const compliance = getComplianceByTender(id);

  if (!tender) return <div className="p-6">Tender not found.</div>;

  return (
    <div className="p-6 space-y-6 max-w-4xl mx-auto">
      {/* Breadcrumb */}
      <div className="flex items-center gap-2 text-sm">
        <Link href="/officer" className="text-muted-foreground hover:text-foreground">Dashboard</Link>
        <span className="text-muted-foreground">/</span>
        <Link href={`/officer/tenders/${id}`} className="text-muted-foreground hover:text-foreground">Evaluation</Link>
        <span className="text-muted-foreground">/</span>
        <span className="font-medium">Report</span>
      </div>

      {/* Report Header */}
      <Card>
        <CardContent className="p-6">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h1 className="text-xl font-bold text-[#1e3a5f]">Bid Evaluation Report</h1>
              <p className="text-sm text-muted-foreground">Generated by BidSure AI · Prototype Report</p>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" className="gap-1">
                <Printer className="h-3.5 w-3.5" /> Print
              </Button>
              <Button size="sm" className="bg-[#1e3a5f] hover:bg-[#152a45] gap-1">
                <Download className="h-3.5 w-3.5" /> Download Report
              </Button>
            </div>
          </div>

          {/* Tender Details */}
          <div className="rounded-md border p-4 space-y-2 mb-4">
            <h2 className="text-sm font-semibold">1. Tender Details</h2>
            <div className="grid grid-cols-2 gap-2 text-sm">
              <div className="flex justify-between"><span className="text-muted-foreground">Tender ID</span><span className="font-mono">{tender.id}</span></div>
              <div className="flex justify-between"><span className="text-muted-foreground">Organization</span><span>{tender.organization}</span></div>
              <div className="flex justify-between"><span className="text-muted-foreground">Title</span><span className="text-right max-w-[250px]">{tender.title}</span></div>
              <div className="flex justify-between"><span className="text-muted-foreground">Value</span><span>{tender.estimatedValueFormatted}</span></div>
            </div>
          </div>

          {/* Bidder Summary */}
          <div className="rounded-md border p-4 mb-4">
            <h2 className="text-sm font-semibold mb-3">2. Bidder Evaluation Summary</h2>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Bidder</TableHead>
                  <TableHead>Compliance</TableHead>
                  <TableHead>Risk</TableHead>
                  <TableHead>Commercial</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>AI Recommendation</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {bids.map((bid) => {
                  const comp = compliance.find(c => c.bidderId === bid.bidderId);
                  const risk = riskAssessments.find(r => r.bidderId === bid.bidderId);
                  const rec = aiRecommendations.find(r => r.bidderId === bid.bidderId);
                  return (
                    <TableRow key={bid.id}>
                      <TableCell className="font-medium text-sm">{bid.bidder.shortName}</TableCell>
                      <TableCell className="font-bold text-sm">{comp?.complianceScore}%</TableCell>
                      <TableCell><StatusBadge status={risk?.riskLevel ?? "LOW"} size="sm" showIcon={false} /></TableCell>
                      <TableCell className="text-sm">{bid.commercial.totalAmountFormatted}</TableCell>
                      <TableCell><StatusBadge status={comp?.overallStatus ?? "PASS"} size="sm" /></TableCell>
                      <TableCell><StatusBadge status={rec?.recommendation ?? "QUALIFY"} size="sm" /></TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </div>

          {/* Sections */}
          {["3. Requirement Compliance Details", "4. Document Verification Summary", "5. Government Verification Status", "6. Risk Assessment", "7. AI Recommendations"].map((section) => (
            <div key={section} className="rounded-md border p-4 mb-4">
              <h2 className="text-sm font-semibold">{section}</h2>
              <p className="text-xs text-muted-foreground mt-1">
                Detailed {section.toLowerCase().split(". ")[1]} information available in full report export.
              </p>
            </div>
          ))}

          {/* Officer Decision */}
          <div className="rounded-md border p-4 mb-4">
            <h2 className="text-sm font-semibold">8. Officer Decision</h2>
            <p className="text-xs text-muted-foreground mt-1">
              Final procurement decisions are recorded by the authorized Procurement Officer
              and are binding as per applicable government procurement rules.
            </p>
          </div>

          {/* Audit Trail */}
          <div className="rounded-md border p-4">
            <h2 className="text-sm font-semibold">9. Audit Trail</h2>
            <p className="text-xs text-muted-foreground mt-1">
              Complete audit trail with timestamps, actors, and actions is maintained for
              every bid evaluation. This ensures full traceability and accountability.
            </p>
          </div>

          <Separator className="my-4" />

          <div className="text-center">
            <p className="text-[10px] text-muted-foreground">
              This report was generated by BidSure AI — Prototype for Smart India Hackathon 2026.
              <br />
              All verification sources are mock/prototype implementations. AI recommendations are advisory only.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
