"""
SatyaSetu Backend — Tender Intelligence API Endpoints (Phase 5)
Provides machine-readable structured tender requirements, normalized fields,
operators, percentage bases, evidence requirements, and exemption metadata.
"""

from typing import Optional
from fastapi import APIRouter, HTTPException, Query, status
from app.schemas.tender_intelligence import (
    StructuredRequirementSchema,
    TenderIntelligenceResponse,
)

router = APIRouter(prefix="/tender-intelligence", tags=["tender-intelligence"])

# Canonical structured tender requirements dataset matching the TypeScript Ground Truth exactly

STRUCTURED_REQUIREMENTS = [
    # --- TENDER 1 (GEM/2026/B/7261466) ---
    {
        "id": "req-t1-001",
        "tenderId": "tender-t1",
        "requirementCode": "REQ-T1-001",
        "category": "FINANCIAL",
        "requirementText": "Bidder Average Annual Turnover in last 3 financial years must be at least ₹5.00 Lakh",
        "normalizedField": "bidder_turnover_annual_avg",
        "requirementType": "FINANCIAL",
        "operator": ">=",
        "thresholdValue": 500000,
        "thresholdUnit": "INR",
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "₹5.00 Lakh",
        "normalizedValue": 500000,
        "mandatory": True,
        "exemptionRule": "MSE/Startup exemption subject to valid DPIIT/Udyam manufacturer registration",
        "exemptionMetadata": {
            "qualifiesFor": ["MSE", "STARTUP"],
            "requiredEvidence": "UDYAM_OR_DPIIT",
            "condition": "Registered manufacturer/service provider matching tender category",
        },
        "evidenceRequired": ["TURNOVER_CERTIFICATE", "AUDITED_BALANCE_SHEET"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7261466.pdf",
        "sourcePage": 3,
        "sourceClause": "Clause 4.1.1 (Financial Eligibility)",
    },
    {
        "id": "req-t1-002",
        "tenderId": "tender-t1",
        "requirementCode": "REQ-T1-002",
        "category": "FINANCIAL",
        "requirementText": "OEM Average Annual Turnover in last 3 financial years must be at least ₹42.00 Lakh",
        "normalizedField": "oem_turnover_annual_avg",
        "requirementType": "OEM",
        "operator": ">=",
        "thresholdValue": 4200000,
        "thresholdUnit": "INR",
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "₹42.00 Lakh",
        "normalizedValue": 4200000,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["OEM_FINANCIAL_STATEMENT", "OEM_TURNOVER_CERTIFICATE"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7261466.pdf",
        "sourcePage": 3,
        "sourceClause": "Clause 4.1.2 (OEM Financial Standing)",
    },
    {
        "id": "req-t1-003",
        "tenderId": "tender-t1",
        "requirementCode": "REQ-T1-003",
        "category": "MANDATORY",
        "requirementText": "Valid tender-specific Manufacturer Authorization Form (MAF) directly executed by the Software OEM",
        "normalizedField": "maf_authorization",
        "requirementType": "DOCUMENT",
        "operator": "VALID",
        "thresholdValue": True,
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "Valid tender-specific MAF from OEM",
        "normalizedValue": True,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["MAF"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7261466.pdf",
        "sourcePage": 4,
        "sourceClause": "Clause 5.2 (OEM Authorization Requirement)",
    },
    {
        "id": "req-t1-004",
        "tenderId": "tender-t1",
        "requirementCode": "REQ-T1-004",
        "category": "EXPERIENCE",
        "requirementText": "Past single qualifying order value must be at least ₹3.675 Lakh (15% of estimated tender value)",
        "normalizedField": "past_single_order_value",
        "requirementType": "EXPERIENCE",
        "operator": "PERCENT_OF",
        "thresholdValue": 367500,
        "thresholdUnit": "INR",
        "thresholdPercentage": 0.15,
        "baseValue": "tender.estimatedValue",
        "originalValue": "15% of tender value (₹3.675 Lakh)",
        "normalizedValue": 367500,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["PURCHASE_ORDER", "COMPLETION_CERTIFICATE"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7261466.pdf",
        "sourcePage": 5,
        "sourceClause": "Clause 6.1 (Past Experience Criteria)",
    },
    {
        "id": "req-t1-005",
        "tenderId": "tender-t1",
        "requirementCode": "REQ-T1-005",
        "category": "EXPERIENCE",
        "requirementText": "Past experience must be with Central/State Govt, PSU, or autonomous government academic institution",
        "normalizedField": "client_type_category",
        "requirementType": "EXPERIENCE",
        "operator": "MATCH",
        "thresholdValue": "GOVERNMENT_OR_PSU",
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "Govt / PSU / Academic Institution",
        "normalizedValue": "GOVERNMENT_OR_PSU",
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["PURCHASE_ORDER", "WORK_ORDER"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7261466.pdf",
        "sourcePage": 5,
        "sourceClause": "Clause 6.2 (Eligible Client Domain)",
    },
    {
        "id": "req-t1-006",
        "tenderId": "tender-t1",
        "requirementCode": "REQ-T1-006",
        "category": "STATUTORY",
        "requirementText": "EMD of ₹49,000 paid or valid MSE Manufacturer registration certificate for exemption",
        "normalizedField": "emd_payment_exemption",
        "requirementType": "EMD",
        "operator": "PERCENT_OF",
        "thresholdValue": 49000,
        "thresholdUnit": "INR",
        "thresholdPercentage": 0.02,
        "baseValue": "tender.estimatedValue",
        "originalValue": "2% of tender value (₹49,000) or MSE Exemption",
        "normalizedValue": 49000,
        "mandatory": True,
        "exemptionRule": "Exemption available exclusively to registered Micro & Small Enterprises (MSEs) in manufacturing/primary service category",
        "exemptionMetadata": {
            "qualifiesFor": ["MSE_MANUFACTURER"],
            "requiredEvidence": "UDYAM_CERTIFICATE",
            "condition": "Micro/Small manufacturer of goods or primary service provider",
        },
        "evidenceRequired": ["EMD_RECEIPT", "UDYAM_CERTIFICATE"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7261466.pdf",
        "sourcePage": 2,
        "sourceClause": "Clause 2.4 (Earnest Money Deposit)",
    },
    {
        "id": "req-t1-007",
        "tenderId": "tender-t1",
        "requirementCode": "REQ-T1-007",
        "category": "PREFERENTIAL",
        "requirementText": "Make in India (MII) declaration with verified OEM local content percentage",
        "normalizedField": "local_content_percentage",
        "requirementType": "MII",
        "operator": "VALID",
        "thresholdValue": True,
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "MII declaration with verified OEM local content",
        "normalizedValue": True,
        "mandatory": False,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["MII_DECLARATION", "OEM_LOCAL_CONTENT_CERT"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7261466.pdf",
        "sourcePage": 7,
        "sourceClause": "Clause 8.1 (Public Procurement Preference to Make in India)",
    },
    {
        "id": "req-t1-008",
        "tenderId": "tender-t1",
        "requirementCode": "REQ-T1-008",
        "category": "TECHNICAL",
        "requirementText": "ICT software installation, license activation, and commissioning within 15 calendar days",
        "normalizedField": "deployment_commissioning_timeline_days",
        "requirementType": "DELIVERY",
        "operator": "<=",
        "thresholdValue": 15,
        "thresholdUnit": "DAYS",
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "15 Calendar Days",
        "normalizedValue": 15,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["TECHNICAL_PROPOSAL", "DELIVERY_UNDERTAKING"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7261466.pdf",
        "sourcePage": 6,
        "sourceClause": "Clause 7.3 (Deployment & Commissioning Timeline)",
    },
    {
        "id": "req-t1-009",
        "tenderId": "tender-t1",
        "requirementCode": "REQ-T1-009",
        "category": "LOCATION",
        "requirementText": "Functional dedicated service centre / technical support office in the state of Rajasthan",
        "normalizedField": "service_center_location",
        "requirementType": "LOCATION",
        "operator": "EXISTS",
        "thresholdValue": "RAJASTHAN",
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "Functional Service Centre in Rajasthan",
        "normalizedValue": "RAJASTHAN",
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["SERVICE_CENTER_DECLARATION", "ADDRESS_PROOF"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7261466.pdf",
        "sourcePage": 8,
        "sourceClause": "Clause 9.4 (Local Service Support Infrastructure)",
    },
    {
        "id": "req-t1-010",
        "tenderId": "tender-t1",
        "requirementCode": "REQ-T1-010",
        "category": "STATUTORY",
        "requirementText": "Non-blacklisting declaration executed on non-judicial stamp paper of ₹100 duly notarized",
        "normalizedField": "non_blacklisting_affidavit",
        "requirementType": "STATUTORY",
        "operator": "VALID",
        "thresholdValue": True,
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "₹100 Notarized Non-Blacklisting Affidavit",
        "normalizedValue": True,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["NOTARIZED_AFFIDAVIT"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7261466.pdf",
        "sourcePage": 9,
        "sourceClause": "Clause 11.2 (Integrity & Non-Debarment Affidavit)",
    },

    # --- TENDER 2 (GEM/2026/B/7364888) ---
    {
        "id": "req-t2-001",
        "tenderId": "tender-t2",
        "requirementCode": "REQ-T2-001",
        "category": "FINANCIAL",
        "requirementText": "Average annual turnover of bidder in last 3 financial years must be at least ₹34.00 Lakh",
        "normalizedField": "bidder_turnover_annual_avg",
        "requirementType": "FINANCIAL",
        "operator": ">=",
        "thresholdValue": 3400000,
        "thresholdUnit": "INR",
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "₹34.00 Lakh",
        "normalizedValue": 3400000,
        "mandatory": True,
        "exemptionRule": "Startup exemption applicable with valid DPIIT Recognition Certificate",
        "exemptionMetadata": {
            "qualifiesFor": ["STARTUP"],
            "requiredEvidence": "DPIIT_RECOGNITION_CERT",
            "condition": "Valid DPIIT recognized startup",
        },
        "evidenceRequired": ["TURNOVER_CERTIFICATE", "AUDITED_BALANCE_SHEET"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7364888.pdf",
        "sourcePage": 3,
        "sourceClause": "Clause 3.1 (Bidder Financial Turnover)",
    },
    {
        "id": "req-t2-002",
        "tenderId": "tender-t2",
        "requirementCode": "REQ-T2-002",
        "category": "EXPERIENCE",
        "requirementText": "Past performance of supplying at least 6,000 units of similar ergonomic assemblies",
        "normalizedField": "past_performance_quantity",
        "requirementType": "QUANTITY",
        "operator": "PERCENT_OF",
        "thresholdValue": 6000,
        "thresholdUnit": "UNITS",
        "thresholdPercentage": 0.10,
        "baseValue": "tender.totalQuantity",
        "originalValue": "10% of tender quantity (6,000 Units)",
        "normalizedValue": 6000,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["PAST_PERFORMANCE_STATEMENT", "SUPPLY_RECORD"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7364888.pdf",
        "sourcePage": 4,
        "sourceClause": "Clause 4.1 (Past Manufacturing & Supply Performance)",
    },
    {
        "id": "req-t2-003",
        "tenderId": "tender-t2",
        "requirementCode": "REQ-T2-003",
        "category": "EXPERIENCE",
        "requirementText": "Past supply proof verified with certified tax invoices and CRAC / user acceptance certificates",
        "normalizedField": "supply_acceptance_proof",
        "requirementType": "DOCUMENT",
        "operator": "EXISTS",
        "thresholdValue": True,
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "Invoices + CRAC / Acceptance Certificate",
        "normalizedValue": True,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["TAX_INVOICE", "CRAC_CERTIFICATE"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7364888.pdf",
        "sourcePage": 4,
        "sourceClause": "Clause 4.2 (Proof of Performance Verification)",
    },
    {
        "id": "req-t2-004",
        "tenderId": "tender-t2",
        "requirementCode": "REQ-T2-004",
        "category": "TECHNICAL",
        "requirementText": "Bidder must be an in-house manufacturer or hold authorized dealership for offered seat components",
        "normalizedField": "manufacturer_classification",
        "requirementType": "TECHNICAL",
        "operator": "VALID",
        "thresholdValue": "MANUFACTURER_OR_AUTHORIZED",
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "In-house Manufacturer or Authorized OEM Dealer",
        "normalizedValue": "MANUFACTURER_OR_AUTHORIZED",
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["UDYAM_MANUFACTURING", "MAF"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7364888.pdf",
        "sourcePage": 5,
        "sourceClause": "Clause 5.1 (Manufacturer Classification)",
    },
    {
        "id": "req-t2-005",
        "tenderId": "tender-t2",
        "requirementCode": "REQ-T2-005",
        "category": "PREFERENTIAL",
        "requirementText": "Make in India Class-I local content minimum 50% with verified calculation certificate",
        "normalizedField": "local_content_percentage",
        "requirementType": "MII",
        "operator": ">=",
        "thresholdValue": 50,
        "thresholdUnit": "PERCENT",
        "thresholdPercentage": 0.50,
        "baseValue": None,
        "originalValue": "Minimum 50% Class-I Local Content",
        "normalizedValue": 0.50,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["COST_AUDITOR_MII_CERT", "MII_DECLARATION"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7364888.pdf",
        "sourcePage": 6,
        "sourceClause": "Clause 6.1 (Make in India Local Content)",
    },
    {
        "id": "req-t2-006",
        "tenderId": "tender-t2",
        "requirementCode": "REQ-T2-006",
        "category": "STATUTORY",
        "requirementText": "EMD of ₹76,000 paid or valid MSE Manufacturer registration certificate for exemption",
        "normalizedField": "emd_payment_exemption",
        "requirementType": "EMD",
        "operator": "PERCENT_OF",
        "thresholdValue": 76000,
        "thresholdUnit": "INR",
        "thresholdPercentage": 0.02,
        "baseValue": "tender.estimatedValue",
        "originalValue": "2% of tender value (₹76,000) or MSE Exemption",
        "normalizedValue": 76000,
        "mandatory": True,
        "exemptionRule": "Exemption available exclusively to registered Micro & Small Enterprises (MSEs) in manufacturing category",
        "exemptionMetadata": {
            "qualifiesFor": ["MSE_MANUFACTURER"],
            "requiredEvidence": "UDYAM_CERTIFICATE",
            "condition": "MSE manufacturing unit",
        },
        "evidenceRequired": ["EMD_RECEIPT", "UDYAM_CERTIFICATE"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7364888.pdf",
        "sourcePage": 2,
        "sourceClause": "Clause 2.3 (EMD Exemption Terms)",
    },
    {
        "id": "req-t2-007",
        "tenderId": "tender-t2",
        "requirementCode": "REQ-T2-007",
        "category": "FINANCIAL",
        "requirementText": "OEM average annual turnover in last 3 financial years must be at least ₹34.00 Lakh",
        "normalizedField": "oem_turnover_annual_avg",
        "requirementType": "OEM",
        "operator": ">=",
        "thresholdValue": 3400000,
        "thresholdUnit": "INR",
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "₹34.00 Lakh",
        "normalizedValue": 3400000,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["OEM_FINANCIAL_STATEMENT"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7364888.pdf",
        "sourcePage": 3,
        "sourceClause": "Clause 3.2 (OEM Annual Turnover)",
    },
    {
        "id": "req-t2-008",
        "tenderId": "tender-t2",
        "requirementCode": "REQ-T2-008",
        "category": "TECHNICAL",
        "requirementText": "Possession of operational manufacturing and testing infrastructure matching specifications",
        "normalizedField": "manufacturing_testing_infrastructure",
        "requirementType": "TECHNICAL",
        "operator": "EXISTS",
        "thresholdValue": True,
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "Operational Manufacturing & Quality Testing Facility",
        "normalizedValue": True,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["PLANT_MACHINERY_LIST", "FACTORY_INSPECTION_RECORD"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7364888.pdf",
        "sourcePage": 7,
        "sourceClause": "Clause 7.2 (Plant and Machinery Verification)",
    },
    {
        "id": "req-t2-009",
        "tenderId": "tender-t2",
        "requirementCode": "REQ-T2-009",
        "category": "STATUTORY",
        "requirementText": "Non-blacklisting declaration executed on non-judicial stamp paper duly notarized",
        "normalizedField": "non_blacklisting_affidavit",
        "requirementType": "STATUTORY",
        "operator": "VALID",
        "thresholdValue": True,
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "₹100 Notarized Non-Blacklisting Affidavit",
        "normalizedValue": True,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["NOTARIZED_AFFIDAVIT"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7364888.pdf",
        "sourcePage": 8,
        "sourceClause": "Clause 8.3 (Non-Blacklisting Declaration)",
    },
    {
        "id": "req-t2-010",
        "tenderId": "tender-t2",
        "requirementCode": "REQ-T2-010",
        "category": "LOCATION",
        "requirementText": "Consistency of registered commercial and manufacturing premises address across statutory documents",
        "normalizedField": "address_veracity_consistency",
        "requirementType": "LOCATION",
        "operator": "MATCH",
        "thresholdValue": "PREMISES_MATCH",
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "Consistent Commercial & Factory Address",
        "normalizedValue": "PREMISES_MATCH",
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["ADDRESS_PROOF", "GST_CERTIFICATE", "UDYAM_CERTIFICATE"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7364888.pdf",
        "sourcePage": 8,
        "sourceClause": "Clause 8.4 (Address Veracity)",
    },
    {
        "id": "req-t2-011",
        "tenderId": "tender-t2",
        "requirementCode": "REQ-T2-011",
        "category": "STATUTORY",
        "requirementText": "DPIIT Recognition Certificate required for claiming Startup turnover & experience exemption",
        "normalizedField": "startup_dpiit_certificate",
        "requirementType": "STARTUP",
        "operator": "VALID",
        "thresholdValue": True,
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "DPIIT Recognition Certificate",
        "normalizedValue": True,
        "mandatory": False,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["DPIIT_RECOGNITION_CERT"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7364888.pdf",
        "sourcePage": 3,
        "sourceClause": "Clause 3.1.1 (Startup Exemption Guidelines)",
    },
    {
        "id": "req-t2-012",
        "tenderId": "tender-t2",
        "requirementCode": "REQ-T2-012",
        "category": "EXPERIENCE",
        "requirementText": "Past experience must be with qualifying Government, PSU, or Public Listed entity",
        "normalizedField": "eligible_client_domain",
        "requirementType": "EXPERIENCE",
        "operator": "MATCH",
        "thresholdValue": "GOVT_PSU_PUBLIC_LISTED",
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "Govt / PSU / Public Listed Entity",
        "normalizedValue": "GOVT_PSU_PUBLIC_LISTED",
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["PURCHASE_ORDER", "CLIENT_CERTIFICATE"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7364888.pdf",
        "sourcePage": 4,
        "sourceClause": "Clause 4.3 (Eligible Client Category)",
    },
    {
        "id": "req-t2-013",
        "tenderId": "tender-t2",
        "requirementCode": "REQ-T2-013",
        "category": "MANDATORY",
        "requirementText": "Valid non-expired tender-specific Manufacturer Authorization Form (MAF) from OEM",
        "normalizedField": "maf_authorization_validity",
        "requirementType": "DOCUMENT",
        "operator": "VALID",
        "thresholdValue": True,
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "Valid Non-Expired OEM MAF",
        "normalizedValue": True,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["MAF"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7364888.pdf",
        "sourcePage": 5,
        "sourceClause": "Clause 5.3 (MAF Validity Standards)",
    },
    {
        "id": "req-t2-014",
        "tenderId": "tender-t2",
        "requirementCode": "REQ-T2-014",
        "category": "TECHNICAL",
        "requirementText": "Commitment to submit physical prototype samples within 10 days of request",
        "normalizedField": "sample_submission_window_days",
        "requirementType": "DELIVERY",
        "operator": "<=",
        "thresholdValue": 10,
        "thresholdUnit": "DAYS",
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "10 Calendar Days",
        "normalizedValue": 10,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["SAMPLE_SUBMISSION_UNDERTAKING"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7364888.pdf",
        "sourcePage": 7,
        "sourceClause": "Clause 7.4 (Sample Submission Window)",
    },

    # --- TENDER 3 (GEM/2026/B/7676747) ---
    {
        "id": "req-t3-001",
        "tenderId": "tender-t3",
        "requirementCode": "REQ-T3-001",
        "category": "FINANCIAL",
        "requirementText": "Bidder average annual turnover in last 3 financial years must be at least ₹3.00 Lakh",
        "normalizedField": "bidder_turnover_annual_avg",
        "requirementType": "FINANCIAL",
        "operator": ">=",
        "thresholdValue": 300000,
        "thresholdUnit": "INR",
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "₹3.00 Lakh",
        "normalizedValue": 300000,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["TURNOVER_CERTIFICATE", "AUDITED_BALANCE_SHEET"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7676747.pdf",
        "sourcePage": 3,
        "sourceClause": "Clause 3.1 (Annual Turnover Criteria)",
    },
    {
        "id": "req-t3-002",
        "tenderId": "tender-t3",
        "requirementCode": "REQ-T3-002",
        "category": "EXPERIENCE",
        "requirementText": "Demonstrated past experience in electrical repair, maintenance, and installation services in Govt/Semi-Govt",
        "normalizedField": "service_domain_experience",
        "requirementType": "EXPERIENCE",
        "operator": "MATCH",
        "thresholdValue": "ELECTRICAL_MAINTENANCE_SERVICES",
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "Electrical Repair & Maintenance AMC in Govt/Semi-Govt",
        "normalizedValue": "ELECTRICAL_MAINTENANCE_SERVICES",
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["WORK_EXPERIENCE_CERTIFICATE", "COMPLETION_CERTIFICATE"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7676747.pdf",
        "sourcePage": 4,
        "sourceClause": "Clause 4.1 (Technical Experience Criteria)",
    },
    {
        "id": "req-t3-003",
        "tenderId": "tender-t3",
        "requirementCode": "REQ-T3-003",
        "category": "STATUTORY",
        "requirementText": "Possession of valid Class-A Electrical Contractor/Supervisor License issued by state licensing board",
        "normalizedField": "electrical_contractor_license",
        "requirementType": "VALIDITY",
        "operator": "VALID",
        "thresholdValue": "CLASS_A_ACTIVE",
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "Active Class-A Electrical License",
        "normalizedValue": "CLASS_A_ACTIVE",
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["ELECTRICAL_LICENSE"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7676747.pdf",
        "sourcePage": 5,
        "sourceClause": "Clause 5.1 (Electrical Contractor Licensing)",
    },
    {
        "id": "req-t3-004",
        "tenderId": "tender-t3",
        "requirementCode": "REQ-T3-004",
        "category": "LOCATION",
        "requirementText": "Registered commercial office / operating service facility located within Gujarat state",
        "normalizedField": "operating_presence_location",
        "requirementType": "LOCATION",
        "operator": "MATCH",
        "thresholdValue": "GUJARAT",
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "Commercial Office / Service Setup in Gujarat",
        "normalizedValue": "GUJARAT",
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["ADDRESS_PROOF", "OFFICE_REGISTRATION"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7676747.pdf",
        "sourcePage": 5,
        "sourceClause": "Clause 5.4 (Local Office Requirement)",
    },
    {
        "id": "req-t3-005",
        "tenderId": "tender-t3",
        "requirementCode": "REQ-T3-005",
        "category": "STATUTORY",
        "requirementText": "Submission of filed GST returns (GSTR-3B) for the latest 3 consecutive months (April, May, June 2026)",
        "normalizedField": "gst_return_filing_compliance",
        "requirementType": "STATUTORY",
        "operator": "VALID",
        "thresholdValue": "3_CONSECUTIVE_MONTHS",
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "GSTR-3B Filed for Apr, May, Jun 2026",
        "normalizedValue": "3_CONSECUTIVE_MONTHS",
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["GSTR3B_RETURN", "GSTN_FILING_RECEIPT"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7676747.pdf",
        "sourcePage": 6,
        "sourceClause": "Clause 6.2 (GST Return Compliance)",
    },
    {
        "id": "req-t3-006",
        "tenderId": "tender-t3",
        "requirementCode": "REQ-T3-006",
        "category": "STATUTORY",
        "requirementText": "Non-blacklisting declaration on ₹100 non-judicial stamp paper duly notarized",
        "normalizedField": "non_blacklisting_affidavit",
        "requirementType": "STATUTORY",
        "operator": "VALID",
        "thresholdValue": True,
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "₹100 Notarized Non-Blacklisting Affidavit",
        "normalizedValue": True,
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["NOTARIZED_AFFIDAVIT"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7676747.pdf",
        "sourcePage": 7,
        "sourceClause": "Clause 7.1 (Non-Blacklisting Affidavit)",
    },
    {
        "id": "req-t3-007",
        "tenderId": "tender-t3",
        "requirementCode": "REQ-T3-007",
        "category": "FINANCIAL",
        "requirementText": "Acceptable financial standing: solvent with no bankruptcy, liquidation, or active NCLT/IBC proceedings",
        "normalizedField": "financial_solvency_standing",
        "requirementType": "FINANCIAL",
        "operator": "VALID",
        "thresholdValue": "SOLVENT_NO_IBC",
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "Solvent standing with zero IBC/NCLT proceedings",
        "normalizedValue": "SOLVENT_NO_IBC",
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["BANK_SOLVENCY_CERT", "LITIGATION_DISCLOSURE"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7676747.pdf",
        "sourcePage": 7,
        "sourceClause": "Clause 7.3 (Financial Solvency & Litigation)",
    },
    {
        "id": "req-t3-008",
        "tenderId": "tender-t3",
        "requirementCode": "REQ-T3-008",
        "category": "TECHNICAL",
        "requirementText": "Compliance to supply 100% ISI/BIS standard certified branded electrical materials and switchgear",
        "normalizedField": "material_isi_quality_spec",
        "requirementType": "TECHNICAL",
        "operator": "VALID",
        "thresholdValue": "100_PERCENT_ISI_BIS",
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "100% ISI/BIS Certified Branded Materials",
        "normalizedValue": "100_PERCENT_ISI_BIS",
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["MATERIAL_QUALITY_UNDERTAKING"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7676747.pdf",
        "sourcePage": 8,
        "sourceClause": "Clause 8.2 (Material Quality Specifications)",
    },
    {
        "id": "req-t3-009",
        "tenderId": "tender-t3",
        "requirementCode": "REQ-T3-009",
        "category": "STATUTORY",
        "requirementText": "Active GST registration under Gujarat State tax jurisdiction (State Code 24)",
        "normalizedField": "gujarat_gst_jurisdiction",
        "requirementType": "STATUTORY",
        "operator": "MATCH",
        "thresholdValue": "STATE_CODE_24",
        "thresholdUnit": None,
        "thresholdPercentage": None,
        "baseValue": None,
        "originalValue": "Active Gujarat State GSTIN (Code 24)",
        "normalizedValue": "STATE_CODE_24",
        "mandatory": True,
        "exemptionRule": None,
        "exemptionMetadata": None,
        "evidenceRequired": ["GST_REGISTRATION_CERTIFICATE"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7676747.pdf",
        "sourcePage": 6,
        "sourceClause": "Clause 6.1 (GST Jurisdiction)",
    },
    {
        "id": "req-t3-010",
        "tenderId": "tender-t3",
        "requirementCode": "REQ-T3-010",
        "category": "STATUTORY",
        "requirementText": "EMD of ₹1,04,000 paid or valid statutory exemption certificate matching service category",
        "normalizedField": "emd_payment_exemption",
        "requirementType": "EMD",
        "operator": "PERCENT_OF",
        "thresholdValue": 104000,
        "thresholdUnit": "INR",
        "thresholdPercentage": 0.02,
        "baseValue": "tender.estimatedValue",
        "originalValue": "2% of tender value (₹1,04,000) or Service MSE Exemption",
        "normalizedValue": 104000,
        "mandatory": True,
        "exemptionRule": "Exemption available to registered MSE service providers in electrical maintenance",
        "exemptionMetadata": {
            "qualifiesFor": ["MSE_SERVICE_PROVIDER"],
            "requiredEvidence": "UDYAM_CERTIFICATE",
            "condition": "Registered MSE in electrical maintenance service domain",
        },
        "evidenceRequired": ["EMD_RECEIPT", "UDYAM_CERTIFICATE"],
        "sourceDocument": "Bid_Document_GEM_2026_B_7676747.pdf",
        "sourcePage": 2,
        "sourceClause": "Clause 2.3 (EMD Terms)",
    },
]

TENDER_MAP = {
    "tender-t1": {
        "bidNumber": "GEM/2026/B/7261466",
        "title": "Procurement of Structural Engineering Software (ETABS, SAFE, SAP2000)",
        "buyer": "Malaviya National Institute of Technology (MNIT) Jaipur",
        "estimatedValue": 2450000,
        "estimatedValueFormatted": "₹24.50 Lakh",
    },
    "GEM/2026/B/7261466": {
        "tenderId": "tender-t1",
        "bidNumber": "GEM/2026/B/7261466",
        "title": "Procurement of Structural Engineering Software (ETABS, SAFE, SAP2000)",
        "buyer": "Malaviya National Institute of Technology (MNIT) Jaipur",
        "estimatedValue": 2450000,
        "estimatedValueFormatted": "₹24.50 Lakh",
    },
    "tender-t2": {
        "bidNumber": "GEM/2026/B/7364888",
        "title": "Supply and Delivery of Ergonomic Seat Assembly and Back Rest Assembly",
        "buyer": "Artificial Limbs Manufacturing Corporation of India (ALIMCO)",
        "estimatedValue": 3800000,
        "estimatedValueFormatted": "₹38.00 Lakh",
    },
    "GEM/2026/B/7364888": {
        "tenderId": "tender-t2",
        "bidNumber": "GEM/2026/B/7364888",
        "title": "Supply and Delivery of Ergonomic Seat Assembly and Back Rest Assembly",
        "buyer": "Artificial Limbs Manufacturing Corporation of India (ALIMCO)",
        "estimatedValue": 3800000,
        "estimatedValueFormatted": "₹38.00 Lakh",
    },
    "tender-t3": {
        "bidNumber": "GEM/2026/B/7676747",
        "title": "Comprehensive Electrical Repair, Maintenance and Installation Services",
        "buyer": "Trade Marks Registry, IP Bhawan, Ghatlodia, Ahmedabad, Gujarat",
        "estimatedValue": 5200000,
        "estimatedValueFormatted": "₹52.00 Lakh",
    },
    "GEM/2026/B/7676747": {
        "tenderId": "tender-t3",
        "bidNumber": "GEM/2026/B/7676747",
        "title": "Comprehensive Electrical Repair, Maintenance and Installation Services",
        "buyer": "Trade Marks Registry, IP Bhawan, Ghatlodia, Ahmedabad, Gujarat",
        "estimatedValue": 5200000,
        "estimatedValueFormatted": "₹52.00 Lakh",
    },
}


@router.get(
    "/requirements",
    response_model=list[StructuredRequirementSchema],
    summary="List Machine-Readable Tender Requirements",
    description="Returns structured tender requirements with normalized fields, operators, and evidence mappings.",
)
def get_all_structured_requirements(
    tender_id: Optional[str] = Query(None, description="Filter by tender ID or bid number")
) -> list[StructuredRequirementSchema]:
    reqs = STRUCTURED_REQUIREMENTS
    if tender_id:
        # Match against internal ID or canonical GeM bid number
        target_id = "tender-t1" if "7261466" in tender_id else ("tender-t2" if "7364888" in tender_id else ("tender-t3" if "7676747" in tender_id else tender_id))
        reqs = [r for r in reqs if r["tenderId"] == target_id]
    return [StructuredRequirementSchema(**r) for r in reqs]


@router.get(
    "/{tender_id:path}/requirements",
    response_model=list[StructuredRequirementSchema],
    summary="Get Structured Requirements for a Specific Tender",
    description="Returns all normalized requirements for a single tender by internal ID or GeM bid number.",
)
def get_tender_requirements_by_id(tender_id: str) -> list[StructuredRequirementSchema]:
    target_id = "tender-t1" if "7261466" in tender_id else ("tender-t2" if "7364888" in tender_id else ("tender-t3" if "7676747" in tender_id else tender_id))
    reqs = [r for r in STRUCTURED_REQUIREMENTS if r["tenderId"] == target_id]
    if not reqs:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Tender requirements not found for identifier: {tender_id}",
        )
    return [StructuredRequirementSchema(**r) for r in reqs]


@router.get(
    "/{tender_id:path}/summary",
    response_model=TenderIntelligenceResponse,
    summary="Get Tender Intelligence Summary",
    description="Returns structured metrics, category counts, and requirements list for a tender.",
)
def get_tender_intelligence_summary(tender_id: str) -> TenderIntelligenceResponse:
    target_id = "tender-t1" if "7261466" in tender_id else ("tender-t2" if "7364888" in tender_id else ("tender-t3" if "7676747" in tender_id else tender_id))
    meta = TENDER_MAP.get(target_id) or TENDER_MAP.get(tender_id)
    if not meta:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Tender not found for identifier: {tender_id}",
        )
    reqs = [r for r in STRUCTURED_REQUIREMENTS if r["tenderId"] == target_id]
    
    return TenderIntelligenceResponse(
        tenderId=target_id,
        bidNumber=meta["bidNumber"],
        title=meta["title"],
        buyer=meta["buyer"],
        estimatedValue=meta["estimatedValue"],
        estimatedValueFormatted=meta["estimatedValueFormatted"],
        totalRequirementsCount=len(reqs),
        mandatoryRequirementsCount=len([r for r in reqs if r["mandatory"]]),
        financialRequirementsCount=len([r for r in reqs if r["category"] == "FINANCIAL" or r["requirementType"] == "FINANCIAL" or r["requirementType"] == "OEM"]),
        technicalRequirementsCount=len([r for r in reqs if r["category"] == "TECHNICAL" or r["requirementType"] == "TECHNICAL" or r["requirementType"] == "DELIVERY"]),
        statutoryRequirementsCount=len([r for r in reqs if r["category"] == "STATUTORY" or r["requirementType"] == "STATUTORY" or r["requirementType"] == "EMD" or r["requirementType"] == "VALIDITY"]),
        experienceRequirementsCount=len([r for r in reqs if r["category"] == "EXPERIENCE" or r["requirementType"] == "EXPERIENCE" or r["requirementType"] == "QUANTITY"]),
        requirements=[StructuredRequirementSchema(**r) for r in reqs],
    )
